export const INITIALIZE = 'INITIALIZE';
export const ADD_TITLE = 'ADD_TITLE';
export const TOOGLE = 'TOOGLE'
export const REMOVE = 'REMOVE'
export const REQUEST_FETCH_ADD='REQUEST_FETCH_ADD';
export const REQUEST_FETCH_ADD_ITEM='REQUEST_FETCH_ADD_ITEM'

export default {
  INITIALIZE,
  ADD_TITLE,
  TOOGLE,
  REMOVE,
  REQUEST_FETCH_ADD,
  REQUEST_FETCH_ADD_ITEM
}
